init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v3.0.$env:APPVEYOR_BUILD_NUMBER" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"
  - ps: Install-Module -Name SignPath

image: Visual Studio 2019

branches:
  except:
    - localbuilding

configuration: ReleaseWindows

environment:
  SIGN_TOKEN:
    secure: CyWk15XNyUCCeNyNoWFUEseZw48+2hTdN1aLsCTGNMYcZgXDjPBhWrNXqSxTKiPQ

pull_requests:
  do_not_increment_build_number: true

build:
  project: radegast.sln
  parallel: true
  verbosity: minimal

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

before_build:
  - nuget restore radegast.sln


after_build:
  - cmd: '7z a -ttar -so Radegast-%TAG_VERSION%.tar bin\ | 7z a -si Radegast-%TAG_VERSION%.tbz'
  - ps: Submit-SigningRequest -InputArtifactPath "Install\RadegastSetup\bin\Release\RadegastSetup.msi" -CIUserToken "$env:SIGN_TOKEN" -OrganizationId "8446d24b-7c29-473d-b13c-83bac9d9db17" -ProjectKey "Radegast" -SigningPolicyKey "Radegast" -OutputArtifactPath "Install\RadegastSetup\bin\Release\RadegastSetup.msi" -Force -WaitForCompletion
  - cmd: 'msbuild "%APPVEYOR_BUILD_FOLDER%\radegast.sln" /t:RadegastBundle /p:Platform="x86" /p:BuildProjectReferences=false /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'
  - ps: Submit-SigningRequest -InputArtifactPath "Install\RadegastBundle\bin\Release\RadegastBundle.exe" -CIUserToken "$env:SIGN_TOKEN" -OrganizationId "8446d24b-7c29-473d-b13c-83bac9d9db17" -ProjectKey "Radegast" -SigningPolicyKey "Radegast" -OutputArtifactPath "RadegastSetup-$env:TAG_VERSION.exe" -Force -WaitForCompletion
  - cmd: copy Install\RadegastSetup\bin\Release\RadegastSetup.msi RadegastSetup-$env:TAG_VERSION.msi


artifacts:
  - path: 'RadegastSetup-*.exe'
    name: 'Radegast Windows Bundle'
    type: Auto
  - path: 'RadegastSetup-*.msi'
    name: 'Radegast Windows MSI'
    type: Auto
  - path: 'Radegast-*.tbz'
    name: 'Radegast Linux'
    type: Auto
