matrix:
  include:
    - language: csharp
      dotnet: 2.0.0
      solution: Radegast.sln
      script:
        - dotnet restore
        - dotnet build -f netstandard2.0 --runtime linux-x64
#    - language: objective-c
#      env:
#        global:
#          - MONO_VERSION=5.2.0
#      install:
#        - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-universal/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg"
#        - export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/Current/bin
#        - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg" -target /
#      before_script:
#        - nuget restore Radegast.sln -Verbosity detailed
#        - nuget update Radegast.sln -Verbosity detailed
#      script:
#        - xbuild /p:Configuration=ReleaseMacOS Radegast.sln
